In [13]:
#Importing necessary libraries

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [2]:
df = pd.read_excel("C:\\Users\\Lenovo\\Downloads\\Spam.xlsx",index_col=False)
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
Category = LabelEncoder()
df['Category'] = Category.fit_transform(df['Category'])

In [4]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
0           4824   4515                             Sorry, I'll call later   
1            744    640  Please call our customer service representativ...   

               
         freq  
Category       
0          30  
1           4

In [5]:
# Under 0 class, there are 4825 reviews and only 4515 are uniques and most frequent are sorry i will call later 
# and occurence is 30

In [6]:
#X = df.drop(['Category'],axis=1)
#y = df['Category']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.Category, test_size = 0.3)

In [10]:
cv = CountVectorizer()
X_train_count = cv.fit_transform(X_train.values)

In [11]:
X_train_count

<3897x7143 sparse matrix of type '<class 'numpy.int64'>'
	with 51889 stored elements in Compressed Sparse Row format>

In [12]:
X_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [14]:
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [15]:
email = ['This is a meeting call at 10.am']

email_count = cv.transform(email)
model.predict(email_count)

array([0])

In [ ]:
## The above 0 means o class which was ham

In [16]:
email_spam = ['high alert claim your money']

email_spam_count = cv.transform(email_spam)
model.predict(email_spam_count)

array([1])

In [ ]:
## Above is spam class

In [18]:
#test model
X_test_count = cv.transform(X_test)
model.score(X_test_count,y_test)

0.9856373429084381